CREATE TABLE IF NOT EXISTS employee (
id SERIAL PRIMARY KEY,
name VARCHAR(100) NOT NULL,
department VARCHAR(100) NOT NULL,
role VARCHAR(100),
status VARCHAR(20) DEFAULT 'Active',
photo_url TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
